import shoes from '../../state/shoes';
import items from '../../state/items';
import { pickRandomlyFromArray } from '../../../helpers';

export default [
  {
    enemies: [pickRandomlyFromArray([shoes.sneaker, shoes.cleat])],
    currentEnemyIndex: 0,
    name: 'A Wild Shoe Appears!',
    scene: 'BattleScene',
    wild: true,
    turn: 0,
    reward: 50,
    playerFirst: true,
  },
  {
    enemies: [pickRandomlyFromArray([shoes.boot, shoes.flats, shoes.slipper])],
    currentEnemyIndex: 0,
    name: 'A Wild Shoe Appears!',
    scene: 'BattleScene',
    wild: true,
    turn: 0,
    reward: 50,
    playerFirst: true,
  },
  {
    enemies: [pickRandomlyFromArray([shoes.boot, shoes.flats, shoes.slipper]), shoes.clown],
    currentEnemyIndex: 0,
    name: 'Trainer Battle',
    scene: 'BattleScene',
    turn: 0,
    reward: 150,
    playerFirst: true,
  },
  {
    name: 'Cobbler',
    scene: 'ShopScene',
    items: [items.shoeBox, items.shoeRepairKit],
  },
  {
    enemies: [shoes.highHeel],
    currentEnemyIndex: 0,
    name: 'A Wild Shoe Appears!',
    scene: 'BattleScene',
    wild: true,
    turn: 0,
    reward: 50,
    playerFirst: true,
  },
  {
    enemies: [pickRandomlyFromArray([shoes.cowboy, shoes.croc])],
    currentEnemyIndex: 0,
    name: 'A Wild Shoe Appears!',
    scene: 'BattleScene',
    wild: true,
    turn: 0,
    reward: 50,
    playerFirst: true,
  },
  {
    enemies: [
      pickRandomlyFromArray([shoes.cowboy, shoes.croc]),
      pickRandomlyFromArray([shoes.cleat, shoes.sandal, shoes.flats]),
      pickRandomlyFromArray([shoes.sneaker, shoes.sandal]),
    ],
    currentEnemyIndex: 0,
    name: 'Trainer Battle',
    scene: 'BattleScene',
    turn: 0,
    reward: 150,
    playerFirst: true,
  },
  {
    name: 'Cobbler',
    scene: 'ShopScene',
    items: [items.shoeBox, items.shoeRepairKit],
  },
  {
    enemies: [
      pickRandomlyFromArray([shoes.cowboy, shoes.croc]),
      pickRandomlyFromArray([shoes.cleat, shoes.sandal, shoes.flats]),
      pickRandomlyFromArray([shoes.sneaker, shoes.sandal]),
      pickRandomlyFromArray([shoes.clown, shoes.highHeel]),
    ],
    currentEnemyIndex: 0,
    name: 'Final Throw Down!',
    scene: 'BattleScene',
    turn: 0,
    reward: 250,
    playerFirst: true,
  },
];
